sudo: required
language: python
python:
    - "2.7"
install:
    - cd backend
    # libraries for scipy
    - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
    # update pip
    - pip install --upgrade pip
    # - pip install numpy :: Numpy is OK
    # !!! It will take 14 minites, so output is needed. But the full output is too long !!!
    - pip install -v scipy | grep ^.*building
    - pip freeze
    # It will take 4 minites
    - pip install matplotlib
    - pip install pylint
    - pip install -r requirements.txt
    
    - node -v
    - npm -v
    - cd ../frontend && npm install
script:
    - cd ../backend
    - pwd
    - pylint --load-plugins pylint_django --errors-only backend
    - python manage.py migrate
    - python manage.py test test
    - cd ../frontend
    - npm test
