sudo: required
language: python
python:
    - "2.7"
install:
    - cd backend
    - pip freeze
    - sudo apt-get install libicu-devel
    - sudo apt-get install blas-devel
    - sudo apt-get install lapack-devel
    - sudo apt-get install texinfo-tex
    - sudo apt-get install libblas-dev
    - sudo apt-get install liblapack-dev
    - sudo apt-get install libatlas-base-dev
    - sudo apt-get install gfortran
    - pip install scipy




    # - sudo apt-get install python-numpy
    # - sudo apt-get install python-scipy
    # - sudo apt-get install python-matplotlib
    - pip install pylint --no-compile
    - pip freeze

    - pip install -r requirements.txt
    - node -v
    - npm -v
    - cd ../frontend && npm install
script:
    - cd ../backend
    - pwd
    - pylint --load-plugins pylint_django --errors-only backend
    - python manage.py migrate
    - python manage.py test test
    - cd ../frontend
    - npm test
