sudo: required
language: python
python:
    - "2.7"
install:
    - cd backend
    # libraries for scipy
    - sudo apt-get install libblas-dev
    - sudo apt-get install liblapack-dev
    - sudo apt-get install libatlas-base-dev
    - sudo apt-get install gfortran
    # update pip
    - pip install --upgrade pip
    # - pip install numpy ::Numpy is OK
    - pip freeze
    # !!! It always deadloop here !!!v
    - pip install -v scipy --no-compile
    - pip freeze

    # - sudo apt-get install python-scipy
    # - sudo apt-get install python-matplotlib
    - pip install pylint --no-compile
    - pip freeze

    - pip install -r requirements.txt
    - node -v
    - npm -v
    - cd ../frontend && npm install
script:
    - cd ../backend
    - pwd
    - pylint --load-plugins pylint_django --errors-only backend
    - python manage.py migrate
    - python manage.py test test
    - cd ../frontend
    - npm test
