language: python
python:
    - "2.7"
install:
    - cd backend
    - pip install pylint --no-compile
    - pip install scipy --no-compile

    - pip install -r requirements.txt
    - node -v
    - npm -v
    - cd ../frontend && npm install
script:
    - cd ../backend
    - pwd
    - pylint --load-plugins pylint_django --errors-only backend
    - python manage.py migrate
    - python manage.py test test
    - cd ../frontend
    - npm test
